controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# For unauthenticated users, redirect to login
# For authenticated users, SpaController will handle all remaining routes
root_shortcut:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'app.index_games'
        ignoreAttributes: false
    priority: -10
