# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.version: '%env(APP_VERSION)%'
    app.telemetry: '%env(APP_TELEMETRY)%'
    admin.email: '%env(ADMIN_EMAIL)%'
    admin.password: '%env(ADMIN_PASSWORD)%'
    spa.backend_api_url: '%env(string:SPA_BACKEND_API_URL)%'
    spa.otel_collector_address: '%env(string:SPA_OTEL_COLLECTOR_ADDRESS)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones        
        
    App\Game\Instrumentation\LoggingInterface:
        factory: ['@App\Instrumentation\Provider', 'provideLogging']
    App\Game\Instrumentation\MetricsInterface:
        factory: ['@App\Instrumentation\Provider', 'provideMetrics']
    App\Game\Instrumentation\TracingInterface:
        factory: ['@App\Instrumentation\Provider', 'provideTracing']

    App\Listener\TraceContextGetter:
        tags:
            - { name: kernel.event_subscriber }

    App\Auth\Permissions:
        arguments: ['%kernel.project_dir%', 'config/permissions.yaml']

    App\Instrumentation\DataCollector\PermissionVotesCollector:
        tags:
            - { name: data_collector, template: 'profiler/permission_votes.html.twig', id: 'app.permission_votes_collector' }

    App\Instrumentation\DataCollector\ArchitectureCollector:
        arguments:
            - '%kernel.project_dir%'
        tags:
            - { name: data_collector, template: 'profiler/architecture.html.twig', id: 'app.architecture_collector' }
