apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
    tier: backend
data:
  APP_ENV: {{ .Values.environment }}
  APP_VERSION: {{ .Chart.Version }}
  APP_SECRET: {{ .Values.backend.secret }}
  ADMIN_EMAIL: {{ .Values.backend.admin.email }}
  ADMIN_PASSWORD: {{ .Values.backend.admin.password }}
  DATABASE_URL: "mysql://root:{{ .Values.database.rootPassword }}@{{ .Release.Name }}-db:3306/app?serverVersion=8.0.31&charset=utf8mb4"
  REDIS_URL: "redis://{{ .Release.Name }}-cache:6379"
  # TODO Use RabbitMQ instead!
  MESSENGER_TRANSPORT_DSN: "doctrine://default"
  # Valid options for APP_TELEMETRY are:
  # "Stdout", "Otel", or "Noop"
  APP_TELEMETRY: "Otel"
  OTEL_PHP_AUTOLOAD_ENABLED: "true"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_LOGS_EXPORTER: "otlp"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.observability.otelCollectorAddress }}
  