apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    app: {{ .Release.Name }}
    tier: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-worker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-worker
        tier: backend
        purpose: worker
    spec:
      terminationGracePeriodSeconds: 3600
      containers:
      #- name: sidecar
      #  volumeMounts:
      #    - mountPath: /share
      #      name: share # must be a shared volume between worker and sidecar!
      #  lifecycle:
      #    preStop:
      #      exec:
      #        command: ["sh", "-c", "while ! [ -f /share/kill_sidecar ]; do sleep 1; done; kill -2 1"]
      #  image: python-flask        
      #  resources:
      #    limits:
      #      cpu: "500m"
      #      memory: "500Mi"
      - name: worker
        image: {{ .Values.backend.image }}
        resources:
          limits:
            cpu: "250m"
            memory: "500Mi"
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "touch /tmp/kill_me"]
        command:
        - /bin/sh
        - -c
        - >
          while ! [ -f /tmp/kill_me ];
            do
            bin/console messenger:consume async --limit=1 --time-limit=60 -vv
          done;
        # touch /share/kill_sidecar        
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-config
        env:
        - name: OTEL_SERVICE_NAME
          value: "worker"