apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-frontend
  name: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
        tier: frontend
        purpose: frontend
    spec:
      containers:
      - image: {{ .Values.frontend.image }}
        name: node
        env:
        - name: BACKEND_API_URL
          value: {{ .Values.frontend.apiAddress }}
        - name: OTEL_COLLECTOR_ADDRESS
          value: {{ .Values.observability.otelCollectorAddress }} 
