apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-initialize
  labels:
    app: {{ .Release.Name }}-initialize
    tier: backend
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z app-db 3306; do echo waiting for db; sleep 2; done']
      - name: create-db
        image: {{ .Values.backend.image }}
        command: ["/bin/sh","-c"]
        args: ["bin/console doctrine:database:create --if-not-exists"]
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-config
      - name: create-schema
        image: {{ .Values.backend.image }}
        command: ["/bin/sh","-c"]
        args: ["bin/console doctrine:schema:update --force"]
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-config
      containers:
      - name: fixtures
        image: {{ .Values.backend.image }}
        command: ["/bin/sh","-c"]
        args: ["bin/console doctrine:fixtures:load -q"]
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-config
      restartPolicy: Never
  backoffLimit: 5