apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app: {{ .Release.Name }}-db
    tier: backend
spec:
  containers:
  - name: mysql
    image: mysql
    env:
      # TODO: Use secret instead!
    - name: MYSQL_ROOT_PASSWORD
      value: secret
    ports:
    - containerPort: 3306
      name: mysql
    volumeMounts:
    - name: persistent-storage
      mountPath: /var/lib/mysql
    resources:
      limits:
        cpu: "500m"
        memory: "2Gi"
  volumes:
  - name: persistent-storage
    emptyDir: {}