apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-cache
  labels:
    app: {{ .Release.Name }}-cache
    tier: backend
spec:
  containers:
  - image: redis:7.2-alpine
    name: redis
    ports:
    - containerPort: 6379
      name: redis
    resources:
      limits:
        cpu: "100m"
        memory: "200Mi"
