apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app: {{ .Release.Name }}-db
    tier: backend
spec:
  containers:
  - name: mysql
    image: mysql
    env:
      # TODO: Use secret instead!
    - name: MYSQL_ROOT_PASSWORD
      value: secret
    ports:
    - containerPort: 3306
      name: mysql
    volumeMounts:
    - name: persistent-storage
      mountPath: /var/lib/mysql
    readinessProbe:
      exec:
        command: ["mysqladmin", "ping", "-h", "127.0.0.1"]
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 2
    livenessProbe:
      exec:
        command: ["mysqladmin", "ping", "-h", "127.0.0.1"]
      initialDelaySeconds: 30
      periodSeconds: 10
    resources:
      limits:
        cpu: "500m"
        memory: "2Gi"
  volumes:
  - name: persistent-storage
    emptyDir: {}