apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-frontend
    tier: frontend
  name: {{ .Release.Name }}-frontend
spec:
  ports:
  - name: 3500-3500
    port: 3500
    protocol: TCP
    targetPort: 3500
    nodePort: {{ .Values.frontend.nodePort }}
  selector:
    app: {{ .Release.Name }}-frontend
  type: NodePort
