apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app: {{ .Release.Name }}-db
    tier: backend
spec:
  selector:
    app: {{ .Release.Name }}-db
  ports:
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
    {{ if eq .Values.environment "dev" }}
    nodePort: {{ .Values.database.nodePort }}
  type: NodePort
    {{ end }}