apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
    tier: backend
  name: {{ .Release.Name }}
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: {{ .Values.backend.nodePort }}
  selector:
    app: {{ .Release.Name }}
  type: NodePort
