apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    tier: telemetry
spec:
  type: NodePort
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
      nodePort: {{ .Values.lgtm.nodePort }}
    - name: otel-grpc
      port: 4317
      targetPort: 4317
    - name: otel-http
      port: 4318
      targetPort: 4318
    - name: prometheus
      port: 9090
      targetPort: 9090
  selector:
    app: {{ .Release.Name }}
