apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lgtm-ingress
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - path: /otel(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: lgtm
            port:
              number: 4318
      - path: /grafana(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: lgtm
            port:
              number: 3000
