apiVersion: v1
kind: Pod
metadata:
  name: lgtm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app: lgtm
spec:
  containers:
  - name: lgtm
    image: {{ .Values.observability.image }}
    ports:
    - containerPort: {{ .Values.observability.ports.grafana }}
      name: grafana
    - containerPort: {{ .Values.observability.ports.otelGrpc }}
      name: otel-grpc
    - containerPort: {{ .Values.observability.ports.otelHttp }}
      name: otel-http
    - containerPort: {{ .Values.observability.ports.prometheus }}
      name: prometheus
    env:
    - name: OTEL_TRACES_EXPORTER
      value: "otlp"
    - name: GF_SERVER_ROOT_URL
      value: {{ .Values.observability.grafanaRootUrl | quote }}
    volumeMounts:
    - name: grafana-datasources
      mountPath: /otel-lgtm/grafana/conf/provisioning/datasources
    - name: grafana-dashboards
      mountPath: /otel-lgtm/grafana/conf/provisioning/dashboards
    livenessProbe:
      httpGet:
        path: /api/health
        port: grafana
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /api/health
        port: grafana
      initialDelaySeconds: 5
      periodSeconds: 5
  volumes:
  - name: grafana-datasources
    configMap:
      name: grafana-datasources
  - name: grafana-dashboards
    configMap:
      name: grafana-provisioning-dashboards
  restartPolicy: Always
