apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fullstack.labels" . | nindent 4 }}
    app: app
spec:
  type: NodePort
  selector:
    {{- include "fullstack.selectorLabels" . | nindent 4 }}
    app: app
  ports:
  - port: 80
    targetPort: http
    nodePort: {{ .Values.nginx.nodePort }}
    name: http
