apiVersion: v1
kind: Service
metadata:
  name: lgtm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fullstack.labels" . | nindent 4 }}
    app: lgtm
spec:
  type: NodePort
  selector:
    {{- include "fullstack.selectorLabels" . | nindent 4 }}
    app: lgtm
  ports:
  - port: 3000
    targetPort: grafana
    nodePort: {{ .Values.observability.nodePorts.grafana }}
    name: grafana
  - port: 4317
    targetPort: otel-grpc
    nodePort: {{ .Values.observability.nodePorts.otelGrpc }}
    name: otel-grpc
  - port: 4318
    targetPort: otel-http
    nodePort: {{ .Values.observability.nodePorts.otelHttp }}
    name: otel-http
  - port: 9090
    targetPort: prometheus
    name: prometheus
  - port: 15672
    targetPort: management
    name: rabbitmq-management
