nelmio_api_doc:
    documentation:
        info:
            title: Fullstack Symfony React
            description: Fullstack demo application
            version: 0.9.3
    areas:
        default:
            path_patterns: [^/api/games]
