{
 "title": "Logs, traces, metrics 📜🔎",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "command_executed_milliseconds", "legendFormat": "Command executed (ms)" },
    { "expr": "message_handled_milliseconds", "legendFormat": "Command executed (ms)" }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "command_executed_milliseconds", "legendFormat": "Command executed (ms)" },
    { "expr": "message_handled_milliseconds", "legendFormat": "Message handled (ms)" }
   ]
  },
  {
   "title": "HTTP Responses",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "my_http_response_total{message=\"success\"}",
     "legendFormat": "success"
    },
    {
     "expr": "my_http_response_total{message=\"client_error\"}",
     "legendFormat": "4xx"
    },
    {
     "expr": "my_http_response_total{message=\"server_error\"}",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Backend",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{service_name=\"backend\"} | channel = \"app\" | detected_level > 100"
    }
   ]
  },
  {
   "title": "Worker",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{service_name=\"worker\"} | channel = \"app\" | detected_level > 100"
    }
   ]
  },
  {
   "title": "Traces (API)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "filters": [
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": "POST api.add_game",
       "valueType": "string"
      },
      { "id": "337df8fa", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{name=~\"^(GET|POST|PUT|DELETE|PATCH) api.*\"}",
     "tableType": "traces"
    }
   ]
  }
 ]
}