# Application Environment
environment: prod

# Backend Application
backend:
  image: fullstack-symfony-react:0.9.2
  replicas: 1
  nodePort: 30100
  admin:
    email: "admin@example.com"
    password: "secret"
  secret: "5fb106d07c5b59845136ac75b26a925f"

# Frontend Application
frontend:
  image: fullstack-symfony-react-web:0.9.2
  replicas: 1
  nodePort: 30200
  apiAddress: "http://localhost:30100/api"

# Database
database:
  rootPassword: "secret"
  nodePort: 30201

# Cache
cache:
  nodePort: 30202

# Observability & Telemetry
# ATTENTION: <telemetry> must match the service name of the telemtry deployment!
observability:
  otelCollectorAddress: "http://telemetry:4318"
