apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullstack.fullname" . }}-app-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fullstack.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.global.environment }}
  {{- range $key, $value := .Values.app.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
